---

- name: Install apt-get updates
  command: apt-get update

- name: Install additional packages
  apt: name={{item}} state=present
  with_items:
   - git
   - vim
   - fping
   - openssh-server
   - bridge-utils
   - lsof
   - lvm2
   - sudo
   - tcpdump

- name: Create Directory for SSH-KEY
  command: mkdir -p /root/.ssh

- name: Copy private key to host
  copy: src=id_rsa dest=/root/.ssh mode=0600

- name: Copy public key to host
  copy: src=id_rsa.pub dest=/root/.ssh mode=0644

- name: Insert public key to authorized_keys
  shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys

- name: Copying interfaces file
  template: src={{inventory_hostname}}_interfaces dest=/etc/network/interfaces
